version: "3.4"

services:
  db:
    container_name: thread-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: thread-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
